version: '2'
services:
  db:
    container_name: db
    image: postgres:11
    tmpfs:
      - /var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres